import { test, expect, Page } from '@playwright/test';

type TestParams = {
  baseUrl: string;
  vendor: string;
  device: string;
};

export const sharedTest = test.extend<TestParams>({
  baseUrl: '',
  vendor: '',
  device: '',
});

export const claMrhTest = async ({ page, baseUrl, vendor, device }: { page: Page, baseUrl: string, vendor: string, device: string }) => {
  await page.goto(`${baseUrl}${vendor}/mrh/full/quote`);
  await page.goto(`${baseUrl}${vendor}/mrh/full/quote/choixHabitation`);
  await expect(page.getByLabel('Decline cookies')).toBeVisible();
  await page.getByLabel('Decline cookies').click();
  await expect(page.getByRole('heading', { name: 'Assurance habitation' })).toBeVisible();
  await expect(page.getByText('Je souhaite assurer ?')).toBeVisible();
  await page.getByRole('button', { name: 'Ma résidence principale' }).click();
  await expect(page.getByRole('button', { name: 'Un appartement' })).toBeVisible();
  await page.getByRole('button', { name: 'Un appartement' }).click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Je suis' })).toBeVisible();
  await page.getByRole('button', { name: 'Locataire' }).click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Nombre de pièces à assurer' })).toBeVisible();
  await page.getByLabel('', { exact: true }).selectOption('5');
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Code postal' })).toBeVisible();
  await page.getByPlaceholder('Code postal, nom de la ville').fill('13100');
  await page.getByRole('option', { name: '- Le Tholonet' }).click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Coordonnées' })).toBeVisible();
  await page.getByLabel('Civilité').selectOption('M.');
  await page.getByLabel('Nom', { exact: true }).click();
  await page.getByLabel('Nom', { exact: true }).fill('Mascarpone');
  await page.getByLabel('Nom', { exact: true }).press('Tab');
  await page.getByLabel('Prénom').fill('Pierre-François');
  await page.getByLabel('E-mail').click();
  await page.getByLabel('E-mail').fill('journeycarene+devcarenemrhparcours@yopmail.com');
  await page.getByLabel('Votre numéro de téléphone').click();
  await page.getByLabel('Votre numéro de téléphone').fill('0613371337');
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Notre proposition tarifaire' })).toBeVisible();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Mon habitation' })).toBeVisible();
  await expect(page.getByText('Parmi ces pièces, combien')).toBeVisible();
  await page.getByLabel('Parmi ces pièces, combien').selectOption('3');
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByText('Le bien à assurer est situé')).toBeVisible();
  await page.getByPlaceholder('rue de la gare, ...').click();
  await page.getByPlaceholder('rue de la gare, ...').fill('5 rue de la gare');
  await page.getByRole('option', { name: 'Rue de la Gare 97490 Saint-Denis' }).click();
  await expect(page.getByText('Le bâtiment a')).toBeVisible();
  await page.getByRole('button', { name: '+ de 10 ans' }).click();
  await expect(page.getByText('L\'appartement / loft se situe')).toBeVisible();
  await page.getByRole('button', { name: 'Etage intermédiaire' }).click();
  await page.getByText('Avez-vous des dépendances ?').click();
  await expect(page.getByText('Avez-vous des dépendances ?')).toBeVisible();
  await page.getByRole('button', { name: 'Oui' }).click();
  await expect(page.getByText('A la même adresse que le bien')).toBeVisible();
  await page.getByRole('button', { name: 'Non' }).nth(1).click();
  await expect(page.getByText('La surface totale des dé')).toBeVisible();
  await page.getByRole('button', { name: 'Oui' }).nth(2).click();
  await expect(page.getByText('Quelle est la surface totale')).toBeVisible();
  await page.getByLabel('Quelle est la surface totale').selectOption('201a300');
  await expect(page.getByText('Quel nombre de dépendances')).toBeVisible();
  await page.getByRole('button', { name: '2', exact: true }).click();
  await page.getByPlaceholder('rue de la gare, ...').nth(1).click();
  await page.getByPlaceholder('rue de la gare, ...').nth(1).fill('6 rue de la gare saint-denis');
  await page.getByRole('option', { name: '6 Rue de la Gare 93160 Noisy-' }).click();
  await page.getByPlaceholder('rue de la gare, ...').nth(2).click();
  await page.getByPlaceholder('rue de la gare, ...').nth(2).fill('7 rue de la gare');
  await page.getByRole('option', { name: 'Rue de la Gare 97490 Saint-Denis' }).click();
  await expect(page.getByText('Mon habitation est-elle équip')).toBeVisible();
  await page.getByRole('button', { name: 'Télésurveillance' }).click();
  await page.getByRole('button', { name: 'Non' }).nth(3).click();
  await expect(page.getByLabel('', { exact: true })).toBeVisible();
  await page.getByLabel('', { exact: true }).selectOption('25000');
  await expect(page.getByText('Je souhaite que les biens pré')).toBeVisible();
  await page.getByLabel('Je souhaite que les biens pré').selectOption('2500');
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Questions complémentaires' })).toBeVisible();
  await expect(page.getByText('Je suis')).toBeVisible();
  await expect(page.getByText('Je suis')).toBeVisible();
  await page.getByLabel('Je suis').selectOption('usufruitier');
  await page.getByRole('button', { name: 'autre' }).click();
  await page.getByLabel('', { exact: true }).selectOption('liberal');
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Antécédents' })).toBeVisible();
  await expect(page.getByText('Je suis déjà assuré(e) pour')).toBeVisible();
  await page.getByRole('button', { name: 'Oui' }).first().click();
  await page.getByRole('button', { name: 'moins d\'un an' }).click();
  await page.getByLabel('Je souhaite être assuré(e) à').fill('2025-01-01');
  await page.getByRole('button', { name: 'Oui' }).nth(1).click();
  await page.getByRole('button', { name: '1' }).click();
  await page.getByRole('button', { name: 'Non' }).nth(2).click();
  await expect(page.getByRole('button', { name: 'Suivant' })).toBeVisible();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await page.getByLabel('Ma date de naissance est le').fill('1980-01-01');
  await page.getByRole('button', { name: 'Oui' }).first().click();
  await page.getByPlaceholder('Code postal, nom de la ville').click();
  await page.getByPlaceholder('Code postal, nom de la ville').fill('dole');
  await page.getByRole('option', { name: '- Dole' }).click();
  await page.getByRole('button', { name: 'Oui' }).nth(1).click();
  await page.getByRole('button', { name: 'Suivant' }).click();
  await expect(page.getByRole('heading', { name: 'Notre proposition tarifaire' })).toBeVisible();
};